# -*- coding: utf-8 -*-
"""Covid-19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QKDuejSoDigSWWNo8cdreM-ZfauphI33
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Covid19Data.csv')

df.head()

df.tail()

df.shape

df.info()

df.describe()

df.count()

df.isnull().sum()

df['Province/State']

df['Province/State'].fillna('Unknown', inplace=True)

df

sns.heatmap(df.isnull())
plt.show()

"""#### Show no. of confirmed,deaths and recovered cases in each region"""

df.groupby('Country/Region')[['Confirmed', 'Deaths', 'Recovered', 'Active']].sum().head(3)

df.groupby('Country/Region')['Confirmed'].sum().sort_values(ascending=False).head(5)

df.groupby('Country/Region')[['Confirmed','Recovered']].sum()

"""#### remove all records where confirmed cases is less than 10"""

df[~(df.Confirmed < 10)]

"""#### In which region max no. of confirmed cases were recorded"""

df.groupby('Country/Region').Confirmed.sum().sort_values(ascending=False).head(10)

"""#### in which region minimum no.of death cases were recorded"""

df.groupby('Country/Region').Deaths.sum().sort_values(ascending = True).tail(9)

"""#### How many confirmed , deaths and recovered cases werre reported from India 29th April 2020"""

df[df['Country/Region'] == "India"]

"""#### Sort the entire data according to the confirmed cases in ascending order"""

df.sort_values(by = "Confirmed",ascending = True)

"""#### Sort the data as per the Recovered cases in descending order"""

df.sort_values(by ="Recovered", ascending = False)

"""#### Top 10 Countries by Confirmed Cases"""

top_confirmed = df.groupby('Country/Region')['Confirmed'].sum().sort_values(ascending=False).head(10)

top_confirmed.plot(kind='bar', figsize=(10,5))
plt.title("Top 10 Countries by Confirmed Cases")
plt.ylabel("Confirmed Cases")
plt.show()

"""#### Deaths vs Recovered Comparison"""

country_data = df.groupby('Country/Region')[['Deaths','Recovered']].sum().head(10)

country_data.plot(kind='bar', figsize=(10,5))
plt.title("Deaths vs Recovered Cases")
plt.show()

"""#### Correlation Heatmap"""

sns.heatmap(df[['Confirmed','Deaths','Recovered','Active']].corr(),
            annot=True,
            cmap='coolwarm')

plt.title("COVID-19 Correlation Heatmap")
plt.show()

"""#### Active Cases Distribution"""

sns.histplot(df['Active'], bins=30)
plt.title("Active Cases Distribution")
plt.show()

"""#### Pairplot

#### Feature Engineering

RECOVERY RATE
"""

df['Recovery Rate'] = (df['Recovered'] / df['Confirmed']) * 100

df

"""#### Death Rate"""

df['Death Rate'] = (df['Deaths'] / df['Confirmed']) * 100

df